version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu-projeto-dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/nodemodules
